code/routes/web.php
<?php

Auth::routes();
/*Route::get('/', function () {
    return view('home');
});*/

// =========================== MAIN SITE / FRONT END ROUTES ======================================

Route::get('/', 'HomeController@index')->name('home');

Route::get('about', 'HomeController@showAbout')->name('pages.about');

Route::get('profile', function(){
    return redirect()->route('members.show', auth()->id());
})->name('user.profile');

Route::get('verification', 'Auth\VerificationController@showVerificationForm')->name('verification.showVerificationForm');
Route::post('verification', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('verification/{activation_code}', 'Auth\VerificationController@activate')->name('verification.activate');

Route::get('refer/{invite_code}', function($inviteCode){
    return redirect()->route('register', ['invite_code' => $inviteCode]);
})->name('refer');

Route::group(['middleware' => ['auth']], function(){
    // Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::get('profile/edit', 'ProfileController@showEditForm')->name('profile.showEditForm');
    Route::patch('profile', 'ProfileController@update')->name('profile.update');
    Route::resource('members', 'MemberController');
    Route::resource('videos', 'VideoController');
});

Route::get('/events', 'EventController@index')->name('events');

Route::get('{post_identifier}', 'PostController@index')->where('post_identifier','blogs|news');
Route::get('{post_identifier}/{slug}', 'PostController@show')->where('post_identifier','blogs|news')->name('posts.show');




// ============================= ADMIN / BACK END ROUTES ========================================

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function(){

    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@authenticate')->name('authenticate');


    Route::group(['middleware' => 'auth.admin'], function(){

        Route::get('/', 'LoginController@checkAdminLogin')->name('home');
        Route::get('/about', 'StaticContentController@aboutUs')->name('about');
        Route::resource('members', 'MemberController');
        Route::post('about/{about}', 'StaticContentController@update')->name('about.update');

        // ======================== POSTS CRUD ===============================
        
        // VIEW POSTS........................
        Route::get('{post_identifier}', 'PostController@index')->where('post_identifier','blogs|news')->name('posts.index');
        
        // CREATE & STORE POSTS....................
        Route::get('{post_identifier}/create', 'PostController@create')->where('post_identifier','blogs|news')->name('posts.create');
        Route::post('{post_identifier}', 'PostController@store')->where('post_identifier','blogs|news')->name('posts.store');


        // EDIT & UPDATE POSTS..............
        Route::get('{post_identifier}/{post}/edit', 'PostController@edit')->where('post_identifier','blogs|news')->name('posts.edit');
        Route::patch('{post_identifier}/{post}', 'PostController@update')->name('posts.update');


        // DELETE POST...........
        Route::delete('{post_identifier}/{post}/delete', 'PostController@destroy')->name('posts.destroy');


        // ===================== EVENTS-CALENDAR CRUD ===============================
        
        // VIEW EVENTS........................
        Route::get('events', 'EventController@index')->name('events.index');

        // CREATE & STORE EVENTS....................
        Route::get('events/create', 'EventController@create')->name('events.create');
        Route::post('events', 'EventController@store')->name('events.store');


        // EDIT & UPDATE EVENT..............
        Route::get('events/{event}/edit', 'EventController@edit')->name('events.edit');
        Route::patch('{event}', 'EventController@update')->name('events.update');


        // DELETE EVENT...........
        Route::delete('events/{event}', 'EventController@destroy')->name('events.destroy');


        // LOGOUT.......
        Route::get('logout', 'LogoutController@logout')->name('logout');

    });

});

code/resources/views/admin/layouts/partials/_footer.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner"> 2018 &copy; stkfortnite.
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->

code/resources/views/admin/layouts/partials/_header.blade.php
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="#">
                <img src="{{ asset('theme/img/logo.png') }}" alt="logo" class="logo-default" /> </a>
            <div class="menu-toggler sidebar-toggler">
               
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN PAGE ACTIONS -->
 
        
        <!-- END PAGE ACTIONS -->
        <!-- BEGIN PAGE TOP -->
        <div class="page-top">
            <!-- BEGIN HEADER SEARCH BOX -->
            <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
           
            <!-- END HEADER SEARCH BOX -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="top-menu">
                <ul class="nav navbar-nav pull-right">
                    <!-- BEGIN NOTIFICATION DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                   
                    <!-- END NOTIFICATION DROPDOWN -->
                    <!-- BEGIN INBOX DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    
                    <!-- END INBOX DROPDOWN -->
                    <!-- BEGIN TODO DROPDOWN -->
                    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                    {{-- <li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="icon-calendar"></i>
                            <span class="badge badge-default"> 3 </span>
                        </a>
                        <ul class="dropdown-menu extended tasks">
                            <li class="external">
                                <h3>You have
                                    <span class="bold">12 pending</span> tasks</h3>
                                <a href="app_todo.html">view all</a>
                            </li>
                            <li>
                                <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">New release v1.2 </span>
                                                <span class="percent">30%</span>
                                            </span>
                                            <span class="progress">
                                                <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">40% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">Application deployment</span>
                                                <span class="percent">65%</span>
                                            </span>
                                            <span class="progress">
                                                <span style="width: 65%;" class="progress-bar progress-bar-danger" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">65% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">Mobile app release</span>
                                                <span class="percent">98%</span>
                                            </span>
                                            <span class="progress">
                                                <span style="width: 98%;" class="progress-bar progress-bar-success" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">98% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">Database migration</span>
                                                <span class="percent">10%</span>
                                            </span>
                                            <span class="progress">
                                                <span style="width: 10%;" class="progress-bar progress-bar-warning" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">10% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">Web server upgrade</span>
                                                <span class="percent">58%</span>
                                            </span>
                                            <span class="progress">
                                                <span style="width: 58%;" class="progress-bar progress-bar-info" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">58% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">Mobile development</span>
                                                <span class="percent">85%</span>
                                            </span>
                                            <span class="progress">
                                                <span style="width: 85%;" class="progress-bar progress-bar-success" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">85% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="task">
                                                <span class="desc">New UI release</span>
                                                <span class="percent">38%</span>
                                            </span>
                                            <span class="progress progress-striped">
                                                <span style="width: 38%;" class="progress-bar progress-bar-important" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">38% Complete</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li> --}}
                    <!-- END TODO DROPDOWN -->

                    <!-- BEGIN USER LOGIN DROPDOWN -->
                   
                    <li class="dropdown dropdown-user">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <img alt="" class="img-circle" src="{{ asset('uploads/users/profile_user.jpg') }}" />
                            <span class="username username-hide-on-mobile"> Admin </span>
                            <span class="glyphicon glyphicon-chevron-down"></span> 
                        </a>
                        <ul class="dropdown-menu dropdown-menu-default">
                            <li>
                                <a href="#"><i class="icon-lock"></i>  Change Password</a>
                            </li>

                            <li class="divider"> </li>

                            <li>
                                <a href="{{ route('admin.logout') }}"><i class="icon-key"></i> Log Out </a>
                            </li>
                        </ul>
                    </li>
                    <!-- END USER LOGIN DROPDOWN -->

                    <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                    
                    {{-- <li class="dropdown dropdown-extended quick-sidebar-toggler">
                        <span class="sr-only">Toggle Quick Sidebar</span>
                        <i class="icon-logout"></i>
                    </li> --}}
                    <!-- END QUICK SIDEBAR TOGGLER -->
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END PAGE TOP -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

code/resources/views/admin/layouts/partials/_sidebar.blade.php
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- END SIDEBAR -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-hover-submenu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li class="nav-item start">
                    <a href="{{ route('admin.home') }}" class="nav-link nav-toggle">
                        <i class="icon-home"></i>
                        <span class="title">Home</span>
                        {{-- <span class="selected"></span>
                        <span class="arrow open"></span> --}}
                    </a>
                </li>
               
                <li class="nav-item  ">
                    <a href="{{ route('admin.about') }}" class="nav-link nav-toggle">
                        <i class="icon-social-dribbble"></i>
                        <span class="title">About</span>
                        <span class="arrow"></span>
                    </a>
                </li>
                <li class="nav-item  ">
                    <a href="{{ route('admin.members.index') }}" class="nav-link nav-toggle">
                        <i class="icon-diamond"></i>
                        <span class="title">Members</span>
                        <span class="arrow"></span>
                    </a>
                </li>
                 <li class="nav-item  ">
                    <a href="{{ route('admin.posts.index', 'blogs') }}" class="nav-link ">
                        <i class="icon-pencil"></i>
                        <span class="title">Blogs</span>
                        <span class="arrow"></span>
                    </a>
                </li>
                <li class="nav-item  ">
                    <a href="{{ route('admin.posts.index', 'news') }}" class="nav-link ">
                        <i class="far fa-newspaper"></i>
                        <span class="title">News</span>
                    </a>
                </li>
                <li class="nav-item  ">
                    <a href="{{ route('admin.events.index') }}" class="nav-link nav-toggle">
                        <i class="icon-calendar"></i>
                        <span class="title">Calendar</span>
                        <span class="arrow"></span>
                    </a>
                </li>
                <li class="nav-item  ">
                    <a href="javascript:;" class="nav-link nav-toggle">
                        <i class="icon-basket"></i>
                        <span class="title">eCommerce</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item  ">
                            <a href="#" class="nav-link ">
                                <i class="icon-home"></i>
                                <span class="title">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item  ">
                            <a href="e#" class="nav-link ">
                                <i class="icon-basket"></i>
                                <span class="title">Orders</span>
                            </a>
                        </li>
                        <li class="nav-item  ">
                            <a href="#" class="nav-link ">
                                <i class="icon-tag"></i>
                                <span class="title">Order View</span>
                            </a>
                        </li>
                        <li class="nav-item  ">
                            <a href="#" class="nav-link ">
                                <i class="icon-graph"></i>
                                <span class="title">Products</span>
                            </a>
                        </li>
                        <li class="nav-item  ">
                            <a href="#" class="nav-link ">
                                <i class="icon-graph"></i>
                                <span class="title">Product Edit</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
        <!-- END SIDEBAR -->
    </div>
    <!-- END SIDEBAR -->