code/routes/web.php
<?php

Auth::routes();
/*Route::get('/', function () {
    return view('home');
});*/

// =========================== MAIN SITE / FRONT END ROUTES ======================================

Route::get('/', 'HomeController@index')->name('home');

Route::get('about', 'HomeController@showAbout')->name('pages.about');

Route::get('profile', function(){
    return redirect()->route('members.show', auth()->id());
})->name('user.profile');

Route::get('verification', 'Auth\VerificationController@showVerificationForm')->name('verification.showVerificationForm');
Route::post('verification', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('verification/{activation_code}', 'Auth\VerificationController@activate')->name('verification.activate');

Route::get('refer/{invite_code}', function($inviteCode){
    return redirect()->route('register', ['invite_code' => $inviteCode]);
})->name('refer');

Route::group(['middleware' => ['auth']], function(){
    // Route::get('profile', 'ProfileController@show')->name('profile.show');
    Route::get('profile/edit', 'ProfileController@showEditForm')->name('profile.showEditForm');
    Route::patch('profile', 'ProfileController@update')->name('profile.update');
    Route::resource('members', 'MemberController');
    Route::resource('videos', 'VideoController');
});

Route::get('/events', 'EventController@index')->name('events');

Route::get('{post_identifier}', 'PostController@index')->where('post_identifier','blogs|news');
Route::get('{post_identifier}/{slug}', 'PostController@show')->where('post_identifier','blogs|news')->name('posts.show');




// ============================= ADMIN / BACK END ROUTES ========================================

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function(){

    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@authenticate')->name('authenticate');


    Route::group(['middleware' => 'auth.admin'], function(){

        Route::get('/', 'LoginController@checkAdminLogin')->name('home');
        Route::get('/about', 'StaticContentController@aboutUs')->name('about');
        Route::resource('members', 'MemberController');
        Route::post('about/{about}', 'StaticContentController@update')->name('about.update');

        // ======================== POSTS CRUD ===============================
        
        // VIEW POSTS........................
        Route::get('{post_identifier}', 'PostController@index')->where('post_identifier','blogs|news')->name('posts.index');
        
        // CREATE & STORE POSTS....................
        Route::get('{post_identifier}/create', 'PostController@create')->where('post_identifier','blogs|news')->name('posts.create');
        Route::post('{post_identifier}', 'PostController@store')->where('post_identifier','blogs|news')->name('posts.store');


        // EDIT & UPDATE POSTS..............
        Route::get('{post_identifier}/{post}/edit', 'PostController@edit')->where('post_identifier','blogs|news')->name('posts.edit');
        Route::patch('{post_identifier}/{post}', 'PostController@update')->name('posts.update');


        // DELETE POST...........
        Route::delete('{post_identifier}/{post}/delete', 'PostController@destroy')->name('posts.destroy');


        // ===================== EVENTS-CALENDAR CRUD ===============================
        
        // VIEW EVENTS........................
        Route::get('events', 'EventController@index')->name('events.index');

        // CREATE & STORE EVENTS....................
        Route::get('events/create', 'EventController@create')->name('events.create');
        Route::post('events', 'EventController@store')->name('events.store');


        // EDIT & UPDATE EVENT..............
        Route::get('events/{event}/edit', 'EventController@edit')->name('events.edit');
        Route::patch('{event}', 'EventController@update')->name('events.update');


        // DELETE EVENT...........
        Route::delete('events/{event}', 'EventController@destroy')->name('events.destroy');


        // LOGOUT.......
        Route::get('logout', 'LogoutController@logout')->name('logout');

    });

});

code/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'type',
        'heading',
        'content',
        'cover_photo'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $dates = [
        'created_at', 'updated_at',
    ];


    /**
     * URL of cover photo
     * @return string
     */
    public function getCoverPhotoUrlAttribute()
    {
        return $this->cover_photo ?
                    asset(self::directory() . '/' .$this->type . '/'. $this->cover_photo) :
                    asset('imgs/placeholders/posts-default.jpg');
    }


    /**
     * Path of cover photo
     * @return string
     */
    public function getCoverPhotoPathAttribute()
    {
        return public_path(self::directory() . DIRECTORY_SEPARATOR .$this->type . DIRECTORY_SEPARATOR. $this->cover_photo);
    }


    /**
     * Directory Location for all posts
     * @return string
     */
    public static function directory()
    {
        return config('paths.post_files');
    }
}

code/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Support\DataProviders\CountriesProvider;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    const ADMIN_EMAIL = 'admin.stkfortnite@gmail.com';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'rank_id',
        'first_name',
        'last_name',
        'email',
        'country_code',
        'password',
        'invite_code',
        'profile_photo',
        'cover_photo',
        'bio',
        'epic_username',
        'epic_platform',
        'is_featured',
        'activation_code',
        'is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * List of Platforms
     */
    const EPIC_PLATFORMS = [
        'PS4',
        'xbox',
        'computer',
        'other'
    ];

    /**
     * Fire User Events
     * @var array
     */
    protected $dispatchesEvents = [
        'creating' => \App\Events\UserCreating::class,
    ];

    /**
     * The attributes that should be should be cast to native values
     *
     * @var array
     */
    protected $casts = [
        'is_active'    => 'boolean'
    ];

    /**
     * Active Users
     * @return string
     */
    public function scopeActive($query)
    {
        return $query->whereIsActive(true);
    }

    /**
     * Active Users
     * @return string
     */
    public function scopeExceptMe($query)
    {
        return $query->where('id', '!=', auth()->id());
    }

    /**
     * Full name of the user
     * @return string
     */
    public function getFullNameAttribute()
    {
        return ucwords(strtolower($this->first_name . ' ' . $this->last_name)) . " ({$this->rank->name})";
    }

    /**
     * Name of the country
     * @return string
     */
    public function getCountryNameAttribute()
    {
        return CountriesProvider::data()[$this->country_code];
    }

    /**
     * Joining month and year in string form
     * @return string
     */
    public function getJoiningMonthYearAttribute()
    {
        return date_format($this->created_at, 'F Y');
    }

    /**
     * Invite code url of the user
     * @return string
     */
    public function getInviteUrlAttribute()
    {
        return route('refer', $this->invite_code);
    }

    /**
     * Invite code url of the user
     * @return string
     */
    public function getProfileUrlAttribute()
    {
        return route('members.show', $this->id);
    }

    /**
     * Listing of Epic Platforms
     * @return array
     */
    public static function epicPlatforms()
    {
        $epicPlatforms = self::EPIC_PLATFORMS;
        return array_combine($epicPlatforms, array_map('ucwords', $epicPlatforms));
    }

    /**
     * Details of Epic platform
     * @return string
     */
    public function getEpicPlatformNameAttribute()
    {
        return ucwords($this->epic_platform);
    }

    /**
     * URL of Profile Photo
     * @return string
     */
    public function getProfilePhotoUrlAttribute()
    {
        return $this->profile_photo 
                ? asset(self::directoryLocation() . '/' . $this->profile_photo)
                : asset('imgs/placeholders/user-image.png');
    }

    /**
     * Directory path of Profile Photo
     * @return string
     */
    public function profilePhotoPath()
    {
        return public_path(self::directoryLocation() . DIRECTORY_SEPARATOR . $this->profile_photo);
    }

    /**
     * URL of Cover Photo
     * @return string
     */
    public function getCoverPhotoUrlAttribute()
    {
        return 
            $this->cover_photo ?
                asset(self::directoryLocation() . '/' . $this->cover_photo) :
                asset('imgs/placeholders/user-cover.png');
    }

    /**
     * Directory path of Cover Photo
     * @return string
     */
    public function coverPhotoPath()
    {
        return public_path(self::directoryLocation() . DIRECTORY_SEPARATOR . $this->cover_photo);
    }

    /**
     * Direction Locations For All User Uploads
     * @return string
     */
    public static function directoryLocation()
    {
        return config('custom.location_user_uploads');
    }

    /**
     * All Referrals sent by the user
     * @return \Illuminate\Support\Collection
     */
    public function referralsSent()
    {
        return $this->hasMany(Referral::class, 'referred_by', 'id');
    }

    /**
     * Videos uploaded by the user
     * @return \Illuminate\Support\Collection
     */
    public function videos()
    {
        return $this->hasMany(Video::class);
    }

    /**
     * Accepted Referrals that were sent by the user
     * @return \Illuminate\Support\Collection
     */
    public function referralsAccepted()
    {
        return $this->referralsSent()->accepted();
    }
    
    /**
     * User who referred this user
     * @return \App\User
     */
    public function referredByReferral()
    {
        return $this->hasOne(Referral::class, 'referred_to', 'id');
    }

    /**
     * Users Referred
     * @return \Illuminate\Support\Collection
     */
    public function usersReferred()
    {
        return $this->belongsToMany(User::class, 'referrals', 'referred_by', 'referred_to');
    }

    /**
     * Users who accepted the referrals
     * @return \Illuminate\Support\Collection
     */
    public function usersAccepted()
    {
        return $this->usersReferred()->whereNotNull('referrals.accepted_at');
    }

    /**
     * Rank details of the user
     * @return App\Rank
     */
    public function rank()
    {
        return $this->belongsTo(Rank::class);
    }

    /**
     * Check if the user is active
     * @return boolean
     */
    public function isActive()
    {
        return $this->is_active == true;
    }

    /**
     * Check if the user is admin
     * @return boolean
     */
    public function isAdmin()
    {
        return $this->email == self::ADMIN_EMAIL;
    }
}

code/app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'file_name',
        'thumbnail_name',
        'duration_in_seconds',
        'title',
        'description',
        'views'
    ];

        /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $attributes = [
        'views' => 0,
        'duration_in_seconds' => 0,
    ];

    /**
     * Videos uploaded by the user
     * @return \Illuminate\Support\Collection
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * URL of Video
     * @return string
     */
    public function getCreatedAtFormattedAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /**
     * URL of Video
     * @return string
     */
    public function getUrlAttribute()
    {
        return asset(self::directoryLocation() . '/' . $this->file_name);
    }

    /**
     * Directory path of video
     * @return string
     */
    public function videoPath()
    {
        return public_path(self::directoryLocation() . DIRECTORY_SEPARATOR . $this->file_name);
    }

    /**
     * URL of Thumbnail
     * @return string
     */
    public function getThumbnailUrlAttribute()
    {
        return asset(self::directoryLocation() . '/' . $this->thumbnail_name);
    }

    /**
     * Directory path of Thumbnail
     * @return string
     */
    public function thumbnailPath()
    {
        return public_path(self::directoryLocation() . DIRECTORY_SEPARATOR . $this->thumbnail_name);
    }

    /**
     * Direction Locations For All Video Uploads
     * @return string
     */
    public static function directoryLocation()
    {
        return config('custom.location_video_uploads');
    }

    /**
     * Increment a view of a video
     * @return null
     */
    public function incrementView()
    {
        $this->update(['views' => $this->views + 1]);
    }
}

code/app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Rank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Support\DataProviders\CountriesProvider;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::whereNotIn('email', ['admin.stkfortnite@gmail.com'])->get();
        return view('admin.members.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $member)
    {
        $rank = Rank::all();
        $countries = CountriesProvider::data();
        return view('admin.members.edit', compact('member','rank','countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $member)
    {
        dd($request->all());
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'start_date' => 'required',
            'end_date' => 'required'
        ]);
        $member->update($request->all());
        return redirect()->route('admin.members.index')->with('success', 'User updated successfully...');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $member)
    {
        $member->delete();
        return redirect()->route('admin.members.index')->with('success','User deleted successfully...');
    }
}

code/resources/views/members/_list.blade.php
@foreach($members as $member)
    <div class="col-12 col-sm-6 col-md-4">
        <div class="card card-lg">
            <div class="card-img">
                <a href="{{ $member->profile_url }}"><img src="{{ $member->profile_photo_url }}" class="card-img-top" alt="Assassin's Creed Syndicate"></a>
            </div>
            <div class="card-block">
                <h4 class="card-title"><a href="{{ $member->profile_url }}">{{ $member->full_name }}</a></h4>
                <div class="card-meta"><span>{{-- June 13, 2017 --}}</span></div>
                <p class="card-text">{{ str_limit($member->bio, 80, '...') }}</p>
            </div>
        </div>
    </div>
@endforeach

code/resources/views/members/index.blade.php
@extends('layouts.app')

@push('css')
    
@endpush

@section('content')
    <section class="p-y-80">
        <div class="container">
            <div class="heading">
                <i class="fa fa-users"></i>
                <h2>Members</h2>
                {{-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> --}}
            </div>
            <div class="row">
                @include('members._list', compact('members'))
                {{-- @foreach($members as $member)
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="card card-lg">
                            <div class="card-img">
                                <a href="{{ $member->profile_url }}"><img src="{{ $member->profile_photo_url }}" class="card-img-top" alt="Assassin's Creed Syndicate"></a>
                                <div class="badge badge-warning">pc</div>
                                <div class="card-likes">
                                    <a href="#">15</a>
                                </div>
                            </div>
                            <div class="card-block">
                                <h4 class="card-title"><a href="game-post.html">{{ $member->full_name }}</a></h4>
                                <div class="card-meta"><span>&nbsp;</span></div>
                                <p class="card-text">{{ str_limit($member->bio, 80, '...') }}</p>
                            </div>
                        </div>
                    </div>
                @endforeach --}}
            </div>
        </div>
    </section>
    <!-- /main -->
@endsection

code/resources/views/members/show.blade.php
@extends('layouts.app')

@push('css')
    <style> .invite-url { word-break: break-word;  } </style>
@endpush

@section('content')
    <section class="hero hero-profile" style="background-image: url('{{ $member->cover_photo_url }}');">
        <div class="overlay"></div>
        <div class="container">
            <div class="hero-block">
                <h5>{{ $member->full_name }}</h5>
                @if($viewingMyProfile)
                    <a class="btn btn-primary btn-sm btn-shadow btn-rounded btn-icon btn-add" href="{{ route('videos.create') }}" data-toggle="tooltip" title="Add Video" role="button"><i class="fa fa-video-camera"></i></a>
                @endif
            </div>
        </div>
    </section>

    <section class="toolbar toolbar-profile" data-fixed="true">
        <div class="container">
            <div class="profile-avatar">
                {{-- <a href="#"> --}}<img src="{{ $member->profile_photo_url }}" alt="">{{-- </a> --}}
                <div class="sticky">
                    <a href="#"><img src="img/user/avatar-sm.jpg" alt=""></a>
                    <div class="profile-info">
                        <h5>Nathan Drake</h5>
                        <span>@nathan</span>
                    </div>
                </div>
            </div>
            <div class="dropdown float-right hidden-md-down">
                {{-- <a class="btn btn-secondary btn-icon btn-sm m-l-25 float-right" href="#" data-toggle="dropdown" role="button"><i class="fa fa-cog"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item active" href="#">Setting</a>
                    <a class="dropdown-item" href="#">Mail</a>
                    <a class="dropdown-item" href="#">Report</a>
                    <a class="dropdown-item" href="#">Block</a>
                </div> --}}
            </div>
            <ul class="toolbar-nav hidden-md-down">
                <li class="active"><a href="#">Videos</a></li>
                {{-- <li><a href="#">About</a></li>
                <li><a href="#">Games (38)</a></li>
                <li><a href="#">Friends (628)</a></li>
                <li><a href="#">Images (23)</a></li>
                <li><a href="#">Videos</a></li>
                <li><a href="#">Groups</a></li>
                <li><a href="#">Forums</a></li> --}}
            </ul>
        </div>
    </section>

    <section class="p-y-30">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 hidden-md-down">
                    <!-- widget about -->
                    <div class="widget widget-about">
                        <h5 class="widget-title">
                            About Me
                             @if($viewingMyProfile)
                                <a class="text-primary" href="{{ route('profile.showEditForm') }}">(Edit)</a>
                            @endif
                            
                        </h5>
                        <p>{{ $member->bio }}</p>
                        <ul>
                            <li><i class="fa fa-clock-o"></i> Joined {{ $member->joining_month_year }}</li>
                            <li><i class="fa fa-map-marker"></i> {{ $member->country_name }}</li>
                            <li><a href="mailto:{{ $member->email }}"><i class="fa fa-envelope"></i> {{ $member->email }}</a></li>
                            @if($member->epic_username)
                                <li><i class="fa fa-user-secret"></i> {{ $member->epic_username }}</li>
                            @endif
                            @if($member->epic_platform_name)
                                <li><i class="fa fa-gamepad"></i> {{ $member->epic_platform_name }}</li>
                            @endif
                            <li>
                                <small><i class="fa fa-link"></i><a class="invite-url text-primary" href="{{ $member->invite_url }}" target="_blank">{{ $member->invite_url }}</a></small>
                            </li>
                        </ul>
                    </div>

                    @if($membersAcceptedCount = $member->usersAccepted->count())
                        <!-- widget friends -->
                        <div class="widget widget-friends">
                            <h5 class="widget-title">REFERRALS ACCEPTED <span>({{ $membersAcceptedCount }})</span></h5>
                            <ul>
                                @foreach($member->usersAccepted as $user)
                                    <li><a href="{{ $user->profile_url }}" data-toggle="tooltip" title="{{ $user->name }}"><img src="{{ $user->profile_photo_url }}" alt="{{ $user->name }}"></a></li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>

                <div class="col-lg-9">
                    <section>
                        <div class="row row-5">
                            @if(!$videos->count())
                                <div class="col-md-12 col-sm-6 col-md-3">
                                    <h4 class="text-center">No Videos Uploaded</h4>
                                </div>
                            @endif
                            @foreach($videos as $video)
                                <div class="col-12 col-sm-6 col-md-3">
                                    <div class="card card-video">
                                        <div class="card-img">
                                            <a href="{{ route('videos.show', $video->id) }}">
                                            <img src="{{ $video->thumbnail_url }}" alt="{{ $video->title }}">
                                        </a>
                                            {{-- <div class="card-meta">
                                                <span>4:32</span>
                                            </div> --}}
                                        </div>
                                        <div class="card-block">
                                            <h4 class="card-title"><a href="{{ route('videos.show', $video->id) }}">{{ str_limit($video->title, 50, '...') }}</a></h4>
                                            <div class="card-meta">
                                                <span><i class="fa fa-clock-o"></i> {{ $video->created_at_formatted }}</span>
                                                <span>{{ $video->views }} views</span>
                                            </div>
                                            <p>{{ str_limit($video->description, 90, '...') }}</p>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    
                        @if($videos->count())
                            <div class="pagination-results m-t-10">
                                <span>Showing {{ $videos->firstItem() }} to {{ $videos->lastItem() }} of {{ $videos->total() }} videos</span>
                                <nav aria-label="Page navigation">
                                    {{ $videos->links() }}
                                </nav>
                            </div>
                        @endif
                    </section>
                </div>
            </div>
        </div>
    </section>
{{-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div> --}}
@endsection